export class projectExperience{
    name: string;
    description: string;
    duty: string[];
}

export const ProjectExperiences:projectExperience[]=[
    {name:"Hospital Management System",description:"This is a medical institution security operation management platform initiated by the health regulator to manage hospital related information, including hospital fire equipment and dangerous goods troubleshooting. The system includes the web side and the app side, the web side is responsible for the overall management of the hospital, and the app side is responsible for troubleshooting the hidden dangers.",duty:["Learn about potential hazard troubleshooting requirements","Responsible for the front-end development of the app, based on the ionic and angular framework. Use angular module separation to make the program structure clearer, and lazy loading of routing optimizes user experience","Responsible for front-end maintenance of the app, modified code according to customer feedback and new requirements"]},
    {name:"GOSI",description:"The goal of the project is to help customers understand the business logic from the code level, to discover the difference between code and actual business requirements, and to help customers achieve code refactoring. The way to achieve this is to extract the business-level code from the Java code provided by the customer by using the tool developed by our company",duty:["Analyze the customer's code, including the project's architecture and the technology used","Responsible for the update and deployment of tools on the client's remote server","Use makefile to organize workflows and improve work efficiency","Use the tool to extract business-related code based on the customer-provided entry function","Write shell/python scripts instead of repeated manual labor, mainly involving CSV file processing","Write a part of the English project description document, responsible for drawing the workflow diagram and detailed steps for introducing the workflow","Responsible for the communication of some questions, mainly including errors and workflow problems when using the tools"]},
    {name:"RE Web",description:"This is a web-based tool developed by the company, which used for code analysis, processing and refactor of legacy code. It mainly includes measuring the quality of the code from the complexity of the code, dependencies, duplicate code, dead code, etc. and helping engineers analyze the domain of code and make suggestions for code refactoring.",duty:["Deployment of the Docker environment, including making images, creating containers, and writing shell scripts to easily update project versions within the container","Functional testing, including the correctness of the display of interface elements and the verification of functionality","Performance testing, using python and selenium to write scripts for testing the page response time"]},
    {name:"PSM",description:"The main development content of the PSM project is the gateway for the intelligent device to access the LTE network, including the Rx interface protocol and the Diameter protocol in the 3GPP standard. Project development mainly uses UML modeling and C++ language, and integrates third-party Kafka/Redis interface to complete the function implementation",duty:["Learn the requirements and write the corresponding test points according to each requirement","Write test cases using robotframework. The definition of keywords is written in python for integration testing and regression testing","Write a python script for performance testing, use the script to generate a large number of messages that need to be sent to Kafka's topic"]}
]
